### ISSUE TITLE
npm test fails with SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by markwaddle** [nathanboktae/mocha-phantomjs-core#27]
```
$ npm test
> mocha-phantomjs-core@2.0.1 test /Users/mark/src/mocha-phantomjs-core
> mocha --compilers coffee:coffee-script/register test/core.tests.coffee -t 5000

/Users/mark/src/mocha-phantomjs-core/test/core.tests.coffee:54
'returns a failure code and shows usage when no args are given', function*() {
                                                                         ^
SyntaxError: Unexpected token *
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.loadFile (/Users/mark/src/mocha-phantomjs-core/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/mark/src/mocha-phantomjs-core/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /usr/local/Cellar/nvm/0.31.2/versions/node/v0.12.16/lib/node_modules/mocha/lib/mocha.js:222:27
  at Array.forEach (native)
  at Mocha.loadFiles (/usr/local/Cellar/nvm/0.31.2/versions/node/v0.12.16/lib/node_modules/mocha/lib/mocha.js:219:14)
  at Mocha.run (/usr/local/Cellar/nvm/0.31.2/versions/node/v0.12.16/lib/node_modules/mocha/lib/mocha.js:487:10)
  at Object.<anonymous> (/usr/local/Cellar/nvm/0.31.2/versions/node/v0.12.16/lib/node_modules/mocha/bin/_mocha:458:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

npm ERR! Test failed.  See above for more details.
```

```
$ npm list                                                                                                                                       
mocha-phantomjs-core@2.0.1 /Users/mark/src/mocha-phantomjs-core
├── bluebird@2.9.24
├─┬ chai@2.2.0
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
├─┬ co-mocha@1.1.0
│ ├── co@4.6.0
│ └── is-generator@1.0.3
├── coffee-script@1.9.1
├── UNMET PEER DEPENDENCY mocha@>=1.18 <3
├── mocha-phantomjs@4.1.0 extraneous
└── requirejs@2.1.20

npm ERR! peer dep missing: mocha@>=1.18 <3, required by co-mocha@1.1.0
npm ERR! extraneous: mocha-phantomjs@4.1.0 /Users/mark/src/mocha-phantomjs-core/node_modules/mocha-phantomjs
```

I'm on Mac OS Sierra 10.12.1, so I need to use phantomjs 2.

```
$ phantomjs --version                                                                                                                            
2.1.1
```

**Comment by nathanboktae** [comment]
Phantomjs 2 doesn't support ES6. Use ES5 or compile with babel or the like.

**Comment by markwaddle** [comment]
any suggestions on how to do so? thanks!

**Comment by markwaddle** [comment]
@nathanboktae: after some more consideration, it is unclear to me what i am doing wrong. i expected to be able to pull the latest from master and run the tests with `npm test`. is there something i am missing?

**Comment by nathanboktae** [comment]
This is not the place to explain how JavaScript and browsers work so I'll be brief. PhantomJS 2 is a headless browser based on QT5 WebKit and JavaScriptCore. JavaScript (officially called ECMAScript) is evolving. You are using generator functions, a feature of ES6. [PhantomJS 2 only supports ES5](http://kangax.github.io/compat-table/es6/#phantom) - but will in 2.5 according to ariya/phantomjs#14506
